# Generated by Django 4.2 on 2023-04-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('snippet', models.TextField()),
                ('image', models.TextField(null=True)),
                ('level', models.TextField()),
                ('totalResults', models.FloatField()),
                ('count', models.FloatField()),
                ('startIndex', models.FloatField()),
            ],
        ),
    ]
